name: adhoc-test

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Go Test
        if: ${{ !inputs.skipTests }}
        run: go test -v -count=100 -race -shuffle=on -coverprofile=coverage.txt ./...
